### ISSUE TITLE
The temporary variable 'u' is cleared at the beginning of each iteration of the Parfor loop.

### ISSUE THREAD

**Issue by luxi3225** [MaxVWDV/glacier-image-velocimetry#1]
Hello, it always shows the following warning and error when running, I don't know why, how can I solve it?

Warning: File:C:\Users\ Dell \AppData\Local\Temp\ Dell \ MCRCACHE9.8 \Glacie0\Glacier_Imag\functions\ Image cross correlation\ GivCore. M:423 columns: 26
The temporary variable 'u' is cleared at the beginning of each iteration of the Parfor loop.If you use it before setting 'u', a runtime error will occur.For more information, see Parallel For Loops in MATLAB, "Uninitialized Temporary Variables."
Warning: File:C:\Users\ Dell \AppData\Local\Temp\ Dell \ MCRCACHE9.8 \Glacie0\Glacier_Imag\functions\ Image cross correlation\ GivCore. M:423 columns: 28
The temporary variable 'v' is cleared at the beginning of each iteration of the Parfor loop.If you use 'v' before setting it, a runtime error will occur.For more information, see Parallel For Loops in MATLAB, "Uninitialized Temporary Variables."
Warning: File:C:\Users\ Dell \AppData\Local\Temp\ Dell \ MCRCACHE9.8 \Glacie0\Glacier_Imag\functions\ Image cross correlation\ GivCore. M:423:30
The temporary variable 'SNR' is cleared at the beginning of each iteration of the Parfor loop.If you use 'SNR' before setting it, a runtime error will occur.For more information, see Parallel For Loops in MATLAB, "Uninitialized Temporary Variables."
Warning: File:C:\Users\ Dell \AppData\Local\Temp\ Dell \ MCRCACHE9.8 \Glacie0\Glacier_Imag\functions\ Image cross correlation\ GivCore. M:423 columns: 34
The temporary variable 'PKR' is cleared at the beginning of each iteration of the Parfor loop.If you use 'PKR' before setting it, a runtime error will occur.For more information, see Parallel For Loops in MATLAB, "Uninitialized Temporary Variables."
Function or variable 'column_v' is not recognized.
Error givCore (line 624)
Error GIV_GUI_main (line 66)
Error GIV_GUI_initialize/plotButtonPushed2 (line 964)
Error GIV_GUI_initialize & gt;@(btn,event)plotButtonPushed2(btn) (line 782)

**Comment by MaxVWDV** [comment]
Error discussed via email. For anyone else who receives a similar error message, check that:
1) Your 'Ideal resolution of output data' is set to a larger value than the resolution of your imagery. An automated error checking for this will be added in the next GIV release.
2) That your 'mask' and 'save_image' files are the same size (same number of rows and columns of pixels) as your images themselves. If not followed, this will also cause errors, or inaccurate cropping of areas of interest.

Note that the 'Warnings' (shown in orange if you are using MATLAB) are not a problem, and will not prevent GIV from running.
