### ISSUE TITLE
Errors during processing `Error while evaluating Button PrivateButtonPushedFc`

### ISSUE THREAD

**Issue by jkittner** [MaxVWDV/glacier-image-velocimetry#2]
Hey, thank you for your great tool, I got it working for one region and I am now trying to apply this for a different region using the same methods and way to export the Sentinel images from the EO Browser as before. Also using your [custom script](https://raw.githubusercontent.com/MaxVWDV/Sentinel-EO-custom-glacier/main/Sent2_glacier_visualisation.txt) but using bands 8, 4, 3, instead of just 8.
However, I am now getting these errors (below) when trying to process my images. You can find the data I used on [GoogleDrive](https://drive.google.com/file/d/1w3tOWvzwOHg-qlYJFBDfHE77YjmU_cVC/view?usp=sharing) so maybe you can reproduce this or guide me where I am doing something wrong.
```
Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 6).
Warning: File: C:\Users\jonas\AppData\Local\Temp\jonas\mcrCache9.8\Glacie0\Glacier_Imag\functions\image cross correlation\GIVcore.m Line: 428 Column: 26
The temporary variable 'u' will be cleared at the beginning of each iteration of the parfor-loop. If 'u' is used before it is set, a runtime error will occur. For more information, see Parallel for Loops in MATLAB, "Uninitialized Temporaries".
Warning: File: C:\Users\jonas\AppData\Local\Temp\jonas\mcrCache9.8\Glacie0\Glacier_Imag\functions\image cross correlation\GIVcore.m Line: 428 Column: 28
The temporary variable 'v' will be cleared at the beginning of each iteration of the parfor-loop. If 'v' is used before it is set, a runtime error will occur. For more information, see Parallel for Loops in MATLAB, "Uninitialized Temporaries".
Warning: File: C:\Users\jonas\AppData\Local\Temp\jonas\mcrCache9.8\Glacie0\Glacier_Imag\functions\image cross correlation\GIVcore.m Line: 428 Column: 30
The temporary variable 'snr' will be cleared at the beginning of each iteration of the parfor-loop. If 'snr' is used before it is set, a runtime error will occur. For more information, see Parallel for Loops in MATLAB, "Uninitialized Temporaries".
Warning: File: C:\Users\jonas\AppData\Local\Temp\jonas\mcrCache9.8\Glacie0\Glacier_Imag\functions\image cross correlation\GIVcore.m Line: 428 Column: 34
The temporary variable 'pkr' will be cleared at the beginning of each iteration of the parfor-loop. If 'pkr' is used before it is set, a runtime error will occur. For more information, see Parallel for Loops in MATLAB, "Uninitialized Temporaries".
Index in position 1 exceeds array bounds.

Error in GIVcore (line 80)

Error in GIV_GUI_main (line 66)

Error in GIV_GUI_initialize/plotButtonPushed2 (line 965)

Error in GIV_GUI_initialize>@(btn,event)plotButtonPushed2(btn) (line 783)

Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 382)
Error while evaluating Button PrivateButtonPushedFcn.
```

**Comment by MaxVWDV** [comment]
Hi Jonas,

Glad GIV is useful for your work. I double checked that error, and it looks like the problem is in the georeferencing file attached to the images - it does not have any lat-long data in it.
![image](https://user-images.githubusercontent.com/53457451/124122646-3d061a80-da6e-11eb-8991-a5b8fe294f98.png)
Try changing the image Coordinate system in Sentinel EO browser from Popular Web Mercator to WGS 84, and it should work.
![image](https://user-images.githubusercontent.com/53457451/124123021-ab4add00-da6e-11eb-89d4-ea0441cc5712.png)
The images look well adapted for feature tracking otherwise - and Viedma has lots of nice surface features. Let me know if you have any luck after the changes.

Cheers -Max

**Comment by jkittner** [comment]
This did work, thank you so much for your help. The other images do have some georeference, but it is in meters maybe that's an issue?

Do you think this is a valid medium quality result?
![Mean Velocity](https://user-images.githubusercontent.com/54631600/124149938-5cfb0580-da91-11eb-9463-de367ac98e0c.png)
